import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Providers from "./Providers";
import { ThemeProvider } from "@/components/ui/theme-provider"
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          themes={[
            "light",
            "red-dark",
            "green-dark",
            "netflix-dark",
            "nature",
            "nature-dark",
            "dracula",
            "dracula-dark",
            "laracon-dark",
            "gold",
            "gold-dark",
            "discord",
            "discord-dark",
          ]}
        >
          <Providers>
            <Navbar />
            {children}
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
